// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpmPwsANWTPihU2I0CLnj2-hICHspl1oQ',
    appId: '1:119024234716:web:a3bf1ef218d28b70cc8419',
    messagingSenderId: '119024234716',
    projectId: 'aoc-fr-ebe73',
    authDomain: 'aoc-fr-ebe73.firebaseapp.com',
    storageBucket: 'aoc-fr-ebe73.appspot.com',
    measurementId: 'G-920HBHT25F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6WBr3OwUZTfEd_jJr2YaEnwYKDw1dEWw',
    appId: '1:119024234716:android:d9e624bec091109ccc8419',
    messagingSenderId: '119024234716',
    projectId: 'aoc-fr-ebe73',
    storageBucket: 'aoc-fr-ebe73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoWyizFMtN9uhAr1loXdFsejIl3y9BamM',
    appId: '1:119024234716:ios:7452d4ad1b33c8facc8419',
    messagingSenderId: '119024234716',
    projectId: 'aoc-fr-ebe73',
    storageBucket: 'aoc-fr-ebe73.appspot.com',
    iosBundleId: 'com.example.aocMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoWyizFMtN9uhAr1loXdFsejIl3y9BamM',
    appId: '1:119024234716:ios:24e26a1ecdbe56cccc8419',
    messagingSenderId: '119024234716',
    projectId: 'aoc-fr-ebe73',
    storageBucket: 'aoc-fr-ebe73.appspot.com',
    iosBundleId: 'com.example.aocMobile.RunnerTests',
  );
}
